name: Build
on: [workflow_dispatch, pull_request]
env:
  TERM: xterm-256color

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build - Ubuntu
            runs-on: ubuntu-latest

          - name: Build - Windows (win32)
            runs-on: windows-latest
            cmake-args: -A Win32 -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

          - name: Build - Windows (win64)
            runs-on: windows-latest
            cmake-args: -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

          - name: Build - macOS
            runs-on: macos-latest

    steps:
    - name: Install packages (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y \
          cmake

    - name: Install packages (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install ${{ matrix.packages }} \
          cmake
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1

    - name: Install packages (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install --no-progress `
          cmake

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        clean: true
        submodules: true

    - name: Generate project
      run: cmake -S . -B build ${{ matrix.cmake-args }} -D CMAKE_BUILD_TYPE=MinSizeRel
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.cxx-compiler }}

    - name: Build project
      run: cmake --build build --config MinSizeRel

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: |
          **/*.so
          **/*.dll
          **/*.dylib
        retention-days: 30

    - name: Upload build errors
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: CMake Errors - ${{ matrix.name }}
        path: |
          **/CMakeFiles/CMakeOutput.log
          **/CMakeFiles/CMakeError.log
          **/Testing/Temporary/LastTest.log
        retention-days: 30
